### ISSUE TITLE
GDAC.1.1 introducing data analytics

### ISSUE THREAD

**Issue by hieu6** [hieu6/GDAC#2]
## issue 1

- [x] Video: Welcome to the Google Data Analytics Certificate
- [x] Reading: Program description and course syllabus
- [ ] Reading: Learning Log: Think about data in daily life
- [ ] Video: Introduction to the course
- [ ] Reading: Helpful resources to get started
- [ ] Discussion Prompt: Meet and greet
- [ ] Ungraded Plugin: Your data analytics certificate roadmap
- [ ] Reading: Deciding if you should take the speed track
- [ ] Practice Quiz: Optional: Familiar with data analytics? Take our diagnostic quiz

## issue 2

- [ ] Reading: Optional: Your diagnostic quiz score and what it means
- [ ] Video: Data analytics in everyday life
- [ ] Reading: Case Study: New data perspectives
- [ ] Reading: Learning Log: Consider how data analysts approach tasks
- [ ] Video: Cassie: Dimensions of data analytics
- [ ] Video: What is the data ecosystem?
- [ ] Video: How data informs better decisions
- [ ] Reading: Data and gut instinct
- [ ] Reading: Origins of the data analysis process
- [ ] Practice Quiz: Test your knowledge on the data ecosystem

## issue 3

- [ ] Video: What to expect moving forward
- [ ] Ungraded Plugin: Commit to completing the program
- [ ] Reading: Program surveys
- [ ] Ungraded Plugin: Google Data Analytics Participant Entry Survey
- [ ] Reading: Discussion forums
- [ ] Reading: Get to know your classmates
- [ ] Discussion Prompt: Meet and greet
- [ ] Practice Quiz: Test your knowledge on proper use of the discussion forum
- [ ] Reading: Glossary: Terms and definitions
- [ ] Graded: Weekly challenge 1
